import type { RefundPolicy } from "./types";

export const DEFAULT_POLICIES: RefundPolicy[] = [
  {
    id: "max_refund_value",
    name: "Max refund value",
    description: "Claims above this amount route to human review instead of auto-approval.",
    paramType: "currency",
    value: 50,
    defaultValue: 50,
    enabled: true,
    severity: "review",
  },
  {
    id: "transaction_age_limit",
    name: "Transaction age limit",
    description: "Refunds denied when the original purchase is older than this many days.",
    paramType: "days",
    value: 30,
    defaultValue: 30,
    enabled: true,
    severity: "deny",
  },
  {
    id: "account_warning_threshold",
    name: "Account warning count",
    description: "Accounts at or above this warning count require agent review.",
    paramType: "count",
    value: 2,
    defaultValue: 2,
    enabled: true,
    severity: "review",
  },
  {
    id: "repeat_claim_limit",
    name: "Repeat claim limit (90d)",
    description: "More than this many refund requests in 90 days triggers review.",
    paramType: "count",
    value: 2,
    defaultValue: 2,
    enabled: true,
    severity: "review",
  },
  {
    id: "block_high_risk",
    name: "Block high-risk accounts",
    description: "Automatically deny refunds flagged by fraud scoring.",
    paramType: "toggle",
    value: true,
    defaultValue: true,
    enabled: true,
    severity: "deny",
  },
  {
    id: "require_eligible_orders",
    name: "Require eligible order status",
    description: "Non-eligible orders (partially refunded, disputed) route to review.",
    paramType: "toggle",
    value: true,
    defaultValue: true,
    enabled: true,
    severity: "review",
  },
];
