import type { RoutingPolicy } from "./types";

export const DEFAULT_POLICIES: RoutingPolicy[] = [
  {
    id: "short-chat",
    name: "Short chat → Flash",
    condition: "Input < 100 tokens, simple chat",
    maxTokens: 100,
    taskTypes: ["simple_chat"],
    primaryModelId: "gemini-flash",
    fallbackModelId: "claude-haiku",
    enabled: true,
  },
  {
    id: "summarize",
    name: "Summarization → Flash / mini",
    condition: "Summarization tasks",
    taskTypes: ["summarization"],
    primaryModelId: "gemini-flash",
    fallbackModelId: "gpt-4o-mini",
    enabled: true,
  },
  {
    id: "code",
    name: "Code gen → Pro / Sonnet",
    condition: "Coding or debugging requests",
    taskTypes: ["code_gen"],
    primaryModelId: "gemini-pro",
    fallbackModelId: "claude-sonnet",
    enabled: true,
  },
  {
    id: "reasoning",
    name: "Complex reasoning → Pro",
    condition: "Multi-step analysis, planning",
    taskTypes: ["complex_reasoning"],
    primaryModelId: "gemini-pro",
    fallbackModelId: "gpt-4o",
    enabled: true,
  },
  {
    id: "extract",
    name: "Data extraction → Haiku",
    condition: "Structured JSON / field extraction",
    taskTypes: ["data_extraction"],
    primaryModelId: "claude-haiku",
    fallbackModelId: "gemini-flash",
    enabled: true,
  },
  {
    id: "long-context",
    name: "Long context → Flash",
    condition: "Input > 8K tokens",
    minTokens: 8000,
    primaryModelId: "gemini-flash",
    fallbackModelId: "gemini-pro",
    enabled: true,
  },
];
